// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "Bangalore",
  "venue": "M Chinnaswamy Stadium",
  "capacity": 30,
  "eventTitle": "VIP Connect — Bangalore Leadership Dinner",
  "heroImageUrl": "/venue/long-table.png",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "Bangalore Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Thirty leaders.\\nThe platinum lounge at cricket's cathedral.\\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other’s assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What’s working, what’s not, and what the next twelve months look like.",
    "We gather at the M Chinnaswamy Stadium's platinum lounge as RCB faces Gujarat Titans in one of IPL 2026's defining matches."
  ],
  "agendaItems": [
    {
      "time": "7:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "7:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "7:45 PM",
      "title": "Dinner",
      "description": "Gourmet cuisine and curated cocktails served as cricket's biggest stars battle on the pitch below."
    },
    {
      "time": "10:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "7:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "7:30 PM",
      "label": "Executive session"
    },
    {
      "time": "7:45 PM",
      "label": "Dinner"
    },
    {
      "time": "10:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 30 people. Small enough that everyone speaks, diverse enough that you’ll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you’d wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "M Chinnaswamy Stadium accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they’ll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — Bangalore Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-bangalore.vercel.app",
  "slug": "moloco-event-bangalore",
  "eventSubtitle": "An exclusive evening at IPL 2026's most anticipated clash",
  "venueAddress": "M Chinnaswamy Stadium, Cubbon Park, Bangalore 560001",
  "venueAddressFull": "M Chinnaswamy Stadium, Cubbon Park, Bangalore 560001, Karnataka, India",
  "date": "April 24, 2026",
  "dateFull": "Thursday, April 24",
  "dateISO": "2026-04-24",
  "calendarDateStart": "20260424T190000",
  "calendarDateEnd": "20260424T220000",
  "time": "7:00 PM",
  "timezone": "Asia/Kolkata",
  "timezoneAbbr": "IST",
  "venueDescription": "The M Chinnaswamy Stadium stands as Bangalore's iconic cricket cathedral, home to Royal Challengers Bangalore and witness to legendary IPL moments. Our exclusive platinum lounge offers panoramic views of the action while maintaining an atmosphere of refined luxury. The energy of 40,000 passionate fans creates an electric backdrop for intimate leadership conversations.",
  "venueCapacityNote": "The platinum lounge accommodates thirty leaders in premium comfort with unobstructed views of the pitch.",
  "venueDiningNote": "Curated cocktails and gourmet fare designed to complement the evening's high-stakes cricket action.",
  "venueDirections": "Located in the heart of Cubbon Park, the stadium is accessible via MG Road Metro Station (15-minute walk) or Cubbon Park Metro Station (10-minute walk). Enter through the VIP entrance on Cubbon Road, where our team will escort you to the platinum lounge.",
  "venueExperienceLine": "We gather at the M Chinnaswamy Stadium's platinum lounge as RCB faces Gujarat Titans in one of IPL 2026's defining matches.",
  "dinnerDescription": "Gourmet cuisine and curated cocktails served as cricket's biggest stars battle on the pitch below.",
  "mapsUrl": "https://www.google.com/maps/place/M.+Chinnaswamy+Stadium/@12.978611,77.599722,17z"
};
